spring:
  application:
    name: gym-access-control
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/gym_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:super-secret-key-that-should-be-changed-in-production-and-be-at-least-256-bits-long}
  expiration: 86400000 # 24 hours
